config/routes.rb
Rails.application.routes.draw do
  resources :photos

  resources :musics

  get 'home/index'

  root 'home#index'

  resources :contacts

  resources :shows

  resources :abouts

  resources :news_updates

  resources :home

  resources :musics

  resources :photos

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Safetosay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div id="mainLogo">
    <%= link_to image_tag("main_logo.png"), root_path %>
  </div>


  <div id="contentBox">
    <nav>
      <%= link_to image_tag("news.png",    :class => "navLink"), news_updates_path %>
      <%= link_to image_tag("shows.png",   :class => "navLink"), shows_path %>
      <%= link_to image_tag("music.png",   :class => "navLink"), musics_path %>
      <%= link_to image_tag("photos.png",  :class => "navLink-photos"), photos_path %>
      <%= link_to image_tag("contact.png", :class => "navLink"), contacts_path %>
    </nav>
  
    <div id="pageContent">

      <%= yield %>

    </div>

    <footer>
      <div id="footerLeft">
      
      <%= image_tag("facebookicon.png", :class => "footerIcon") %>
      <%= image_tag("reverbnationicon.png", :class => "footerIcon") %>
      </div>
      
      <div id="footerRight">
      <%= image_tag("githubicon.png", :class => "footerIcon") %>
    </div>
    </footer>
  </div>



</body>
</html>